# /// script
# requires-python = ">=3.12"
# dependencies = [
#   "jinja2>=3.1,<4",
#   "pyyaml>=6,<7",
# ]
# ///

from __future__ import annotations

import argparse
import os
import stat
import sys
import tempfile
from pathlib import Path
from typing import Any

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined


SOURCE_DIR = Path(__file__).resolve().parent
REPOSITORY_DIR = SOURCE_DIR.parent.parent
SKILL_DIR = (
    REPOSITORY_DIR / "packages" / "agent-skills" / "personal" / "codex-subagent-routing"
)
REFERENCES_DIR = SKILL_DIR / "references"
SPEC_PATH = SOURCE_DIR / "lanes.yaml"
TEMPLATE_NAME = "lane.md.j2"
GENERATED_NOTICE = (
    "<!-- Generated by `task skills:routing:generate`; edit "
    "`scripts/codex-subagent-routing/lanes.yaml` or `lane.md.j2`. -->"
)
ALLOWED_FAMILIES = {"native", "cursor", "opencode"}
COMMON_FIELDS = {"slug", "family", "title"}
FAMILY_FIELDS = {
    "native": set(),
    "cursor": {"model", "model_label_pattern"},
    "opencode": {
        "variant",
        "model",
        "model_variable",
        "model_choices_markdown",
        "title_prefix",
    },
}


class SpecError(ValueError):
    pass


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate routing lane references.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report stale generated references without writing them.",
    )
    return parser.parse_args()


def load_lanes() -> list[dict[str, Any]]:
    document = yaml.safe_load(SPEC_PATH.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        raise SpecError("lanes.yaml must contain a mapping")
    if document.get("schema_version") != 1:
        raise SpecError("lanes.yaml must declare schema_version: 1")

    lanes = document.get("lanes")
    if not isinstance(lanes, list) or not lanes:
        raise SpecError("lanes.yaml must contain a non-empty lanes list")

    required = {"slug", "family", "title"}
    seen: set[str] = set()
    for index, lane in enumerate(lanes):
        if not isinstance(lane, dict):
            raise SpecError(f"lane {index} must be a mapping")
        missing = required - lane.keys()
        if missing:
            raise SpecError(f"lane {index} is missing: {', '.join(sorted(missing))}")

        slug = lane["slug"]
        if not isinstance(slug, str) or not slug.replace("-", "").isalnum():
            raise SpecError(f"invalid lane slug: {slug!r}")
        if slug in seen:
            raise SpecError(f"duplicate lane slug: {slug}")
        seen.add(slug)

        family = lane["family"]
        if family not in ALLOWED_FAMILIES:
            raise SpecError(f"unsupported family for {slug}: {family!r}")
        unknown = lane.keys() - COMMON_FIELDS - FAMILY_FIELDS[family]
        if unknown:
            raise SpecError(f"unknown fields for {slug}: {', '.join(sorted(unknown))}")
        if family != "native" and "model" not in lane:
            raise SpecError(f"{slug} must define model")
        if family == "opencode" and "title_prefix" not in lane:
            raise SpecError(f"{slug} must define title_prefix")
        if family == "opencode" and lane.get("variant") not in {"grok", "ollama"}:
            raise SpecError(f"{slug} must define variant as grok or ollama")
        if lane.get("variant") == "ollama":
            ollama_fields = {"model_variable", "model_choices_markdown"}
            missing_ollama = ollama_fields - lane.keys()
            if missing_ollama:
                raise SpecError(
                    f"{slug} is missing: {', '.join(sorted(missing_ollama))}"
                )

    return lanes


def render(lanes: list[dict[str, Any]]) -> dict[Path, str]:
    environment = Environment(
        loader=FileSystemLoader(SOURCE_DIR),
        undefined=StrictUndefined,
        autoescape=False,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    template = environment.get_template(TEMPLATE_NAME)
    outputs: dict[Path, str] = {}
    for lane in lanes:
        rendered = template.render(lane=lane, generated_notice=GENERATED_NOTICE)
        outputs[REFERENCES_DIR / f"{lane['slug']}.md"] = rendered.rstrip() + "\n"
    return outputs


def check(outputs: dict[Path, str]) -> int:
    stale: list[Path] = []
    for path, expected in outputs.items():
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            stale.append(path)

    expected_paths = set(outputs)
    unexpected = [
        path
        for path in REFERENCES_DIR.glob("*.md")
        if path not in expected_paths
        and path.read_text(encoding="utf-8").startswith(GENERATED_NOTICE)
    ]

    if not stale and not unexpected:
        print(f"All {len(outputs)} generated routing references are current.")
        return 0

    for path in stale:
        print(f"stale: {path.relative_to(SKILL_DIR)}", file=sys.stderr)
    for path in unexpected:
        print(f"unexpected generated file: {path.relative_to(SKILL_DIR)}", file=sys.stderr)
    print("Run `task skills:routing:generate`.", file=sys.stderr)
    return 1


def write_atomic(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False

    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
        text=True,
    )
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        mode = stat.S_IMODE(path.stat().st_mode) if path.exists() else 0o644
        os.chmod(temporary_path, mode)
        os.replace(temporary_path, path)
    finally:
        temporary_path.unlink(missing_ok=True)
    return True


def main() -> int:
    args = parse_args()
    try:
        outputs = render(load_lanes())
    except (OSError, SpecError, yaml.YAMLError) as error:
        print(f"routing reference generation failed: {error}", file=sys.stderr)
        return 2

    if args.check:
        return check(outputs)

    changed = [path for path, content in outputs.items() if write_atomic(path, content)]
    for path in changed:
        print(f"generated: {path.relative_to(SKILL_DIR)}")
    if not changed:
        print(f"All {len(outputs)} generated routing references were already current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
